import { BJTNPNIcon, BJTPNPIcon, BoardIcon, CapacitorIcon, DiodeIcon, InductorIcon, JFETNIcon, JFETPIcon, LDRIcon, LEDIcon, NChainDepMOSFETIcon, NChainEnhMOSFETIcon, NodeIcon, PChainDepMOSFETIcon, PChainEnhMOSFETIcon, PhotoDiodeIcon, PolarisedCapacitorIcon, PotentiometerIcon, ResistorIcon, RheostatIcon, SchottkyIcon, TVSDiodeIcon, ThermistorIcon, TrimmerCapacitorIcon, TunnelIcon, VaractorIcon, VariableCapacitorIcon, ZenerIcon } from "@/icons";
import { ComponentProperties, ComponentType, UnitsType } from "@/types";



// Mapa para almacenar contadores por tipo
export const ComponentsMap: Record<ComponentType, ComponentProperties> = {
    [ComponentType.Board]: {
        name: 'Board',
        value: 0,
        category: 'Structure',
        componentType: ComponentType.Board,
        icon: <BoardIcon />,
        unit: UnitsType.Undefined,
        prefix: "",
        reference: "BR",
        type: 'board',
        has_properties: false,
        isReferenceVisible: false,
        isValueVisible: false,
        connectedHandles: [],
        style: {
            height:
                200, width: 200

        },
        size: "small"
    },
    [ComponentType.Node]: {
        name: 'Node',
        value: 0,
        category: 'Structure',
        componentType: ComponentType.Node,
        icon: <NodeIcon />,
        unit: UnitsType.Undefined,
        prefix: "",
        reference: "N",
        type: 'nodeComponent',
        has_properties: false,
        isReferenceVisible: false,
        isValueVisible: false,
        connectedHandles: [false, false, false, false],
        color: 'var(--foreground-color)',
        style: undefined,
        size: "small"
    },
    [ComponentType.Resistor]: {
        name: 'Resistor',
        value: 1,
        category: 'Resistors',
        componentType: ComponentType.Resistor,
        icon: <ResistorIcon />,
        unit: UnitsType.Ohm,
        prefix: "KΩ",
        reference: "R",
        type: 'analogComponent',
        has_properties: true,
        isReferenceVisible: true,
        isValueVisible: true,
        connectedHandles: [false, false],
        style: undefined,
        size: "small"
    },
    [ComponentType.Rheostat]: {
        name: 'Rheostat',
        value: 1,
        category: 'Resistors',
        componentType: ComponentType.Rheostat,
        icon: <RheostatIcon />,
        unit: UnitsType.Ohm,
        prefix: "KΩ",
        reference: "RH",
        type: 'analogComponent',
        has_properties: true,
        isReferenceVisible: true,
        isValueVisible: true,
        connectedHandles: [false, false],
        style: undefined,
        size: "small"
    },
    [ComponentType.Thermistor]: {
        name: 'Thermistor',
        value: 10,
        category: 'Resistors',
        componentType: ComponentType.Thermistor,
        icon: <ThermistorIcon />,
        unit: UnitsType.Ohm,
        prefix: "KΩ",
        reference: "RT",
        type: 'analogComponent',
        has_properties: true,
        isReferenceVisible: true,
        isValueVisible: true,
        connectedHandles: [false, false],
        style: undefined,
        size: "small"
    },
    [ComponentType.Photoresistance]: {
        name: 'Photo Resistance',
        value: 10,
        category: 'Resistors',
        componentType: ComponentType.Photoresistance,
        icon: <LDRIcon />,
        unit: UnitsType.Ohm,
        prefix: "KΩ",
        reference: "LDR",
        type: 'analogComponent',
        has_properties: true,
        isReferenceVisible: true,
        isValueVisible: true,
        connectedHandles: [false, false],
        style: undefined,
        size: "medium"
    },
    [ComponentType.Potentiometer]: {
        name: 'Potentiometer',
        value: 1,
        category: 'Resistors',
        componentType: ComponentType.Potentiometer,
        icon: <PotentiometerIcon />,
        unit: UnitsType.Ohm,
        prefix: "KΩ",
        reference: "R",
        type: 'analogComponent',
        has_properties: true,
        isReferenceVisible: true,
        isValueVisible: true,
        connectedHandles: [false, false],
        style: undefined,
        size: "small"
    },
    [ComponentType.Capacitor]: {
        name: 'Capacitor',
        value: 100,
        category: 'Capacitors',
        componentType: ComponentType.Capacitor,
        icon: <CapacitorIcon />,
        unit: UnitsType.Capacitance,
        prefix: "nF",
        reference: "C",
        type: 'analogComponent',
        has_properties: true,
        isReferenceVisible: true,
        isValueVisible: true,
        connectedHandles: [false, false],
        style: undefined,
        size: "small"
    },
    [ComponentType.PolarisedCapacitor]: {
        name: 'Polarised Capacitor',
        value: 4.7,
        category: 'Capacitors',
        componentType: ComponentType.PolarisedCapacitor,
        icon: <PolarisedCapacitorIcon />
        , unit: UnitsType.Capacitance,
        prefix: "µF",
        reference: "C",
        type: 'analogComponent',
        has_properties: true,
        isReferenceVisible: true,
        isValueVisible: true,
        connectedHandles: [false, false],
        style: undefined,
        size: "small"
    },
    [ComponentType.VariableCapacitor]: {
        name: 'Variable Capacitor',
        value: 100,
        category: 'Capacitors',
        componentType: ComponentType.VariableCapacitor,
        icon: <VariableCapacitorIcon />,
        unit: UnitsType.Capacitance,
        prefix: "µF",
        reference: "VC",
        type: 'analogComponent',
        has_properties: true,
        isReferenceVisible: true,
        isValueVisible: true,
        connectedHandles: [false, false],
        style: undefined,
        size: "small"
    },
    [ComponentType.TrimmerCapacitor]: {
        name: 'Trimmer Capacitor',
        value: 100,
        category: 'Capacitors',
        componentType: ComponentType.TrimmerCapacitor,
        icon: <TrimmerCapacitorIcon />,
        unit: UnitsType.Capacitance,
        prefix: "µF",
        reference: "VC",
        type: 'analogComponent',
        has_properties: true,
        isReferenceVisible: true,
        isValueVisible: true,
        connectedHandles: [false, false],
        style: undefined,
        size: "small"
    },
    [ComponentType.Diode]: {
        name: 'Diode',
        value: 0.7,
        category: 'Diodes',
        componentType: ComponentType.Diode,
        icon: <DiodeIcon />,
        unit: UnitsType.Voltage,
        prefix: "V",
        reference: "D",
        type: 'analogComponent',
        has_properties: true,
        isReferenceVisible: true,
        isValueVisible: true,
        connectedHandles: [false, false],
        style: undefined,
        size: "small"
    },
    [ComponentType.Led]: {
        name: 'LED',
        value: 30,
        category: 'Diodes',
        componentType: ComponentType.Led,
        icon: <LEDIcon />,
        unit: UnitsType.Current,
        prefix: "µA",
        reference: "LED",
        type: 'analogComponent',
        has_properties: true,
        isReferenceVisible: true,
        isValueVisible: true,
        connectedHandles: [false, false],
        style: undefined,
        size: "small", color: '#FF0000'
    },
    [ComponentType.Zener]: {
        name: 'Zener',
        value: 6,
        category: 'Diodes',
        componentType: ComponentType.Zener,
        icon: <ZenerIcon />,
        unit: UnitsType.Current,
        prefix: "V",
        reference: "D",
        type: 'analogComponent',
        has_properties: true,
        isReferenceVisible: true,
        isValueVisible: true,
        connectedHandles: [false, false],
        style: undefined,
        size: "small"
    },
    [ComponentType.Schottky]: {
        name: 'Schottky',
        value: 30,
        category: 'Diodes',
        componentType: ComponentType.Schottky,
        icon: <SchottkyIcon />,
        unit: UnitsType.Current,
        prefix: "V",
        reference: "D",
        type: 'analogComponent',
        has_properties: true,
        isReferenceVisible: true,
        isValueVisible: true,
        connectedHandles: [false, false],
        style: undefined,
        size: "small"
    },
    [ComponentType.Tunnel]: {
        name: 'Tunnel',
        value: 15,
        category: 'Diodes',
        componentType: ComponentType.Tunnel,
        icon: <TunnelIcon />,
        unit: UnitsType.Current,
        prefix: "V",
        reference: "D",
        type: 'analogComponent',
        has_properties: true,
        isReferenceVisible: true,
        isValueVisible: true,
        connectedHandles: [false, false],
        style: undefined,
        size: "small"
    },
    [ComponentType.PhotoDiode]: {
        name: 'Photo Diode',
        value: 6,
        category: 'Diodes',
        componentType: ComponentType.PhotoDiode,
        icon: <PhotoDiodeIcon />,
        unit: UnitsType.Current,
        prefix: "V",
        reference: "D",
        type: 'analogComponent',
        has_properties: true,
        isReferenceVisible: true,
        isValueVisible: true,
        connectedHandles: [false, false],
        style: undefined,
        size: "small"
    },
    [ComponentType.TVSDiode]: {
        name: 'TVS Diode',
        value: 15,
        category: 'Diodes',
        componentType: ComponentType.TVSDiode,
        icon: <TVSDiodeIcon />,
        unit: UnitsType.Current,
        prefix: "V",
        reference: "D",
        type: 'analogComponent',
        has_properties: true,
        isReferenceVisible: true,
        isValueVisible: true,
        connectedHandles: [false, false],
        style: undefined,
        size: "small"
    },
    [ComponentType.Varactor]: {
        name: 'Varactor',
        value: 30,
        category: 'Diodes',
        componentType: ComponentType.Varactor,
        icon: <VaractorIcon />,
        unit: UnitsType.Current,
        prefix: "V",
        reference: "D",
        type: 'analogComponent',
        has_properties: true,
        isReferenceVisible: true,
        isValueVisible: true,
        connectedHandles: [false, false],
        style: undefined,
        size: "small"
    },
    [ComponentType.TransistorBJT_NPN]: {
        name: 'Transistor BJT NPN',
        value: 1,
        category: 'Transistors',
        componentType: ComponentType.TransistorBJT_NPN,
        icon: <BJTNPNIcon />,
        unit: UnitsType.Undefined,
        prefix: "",
        reference: "Q",
        type: 'transistorComponent',
        has_properties: true,
        isReferenceVisible: true,
        isValueVisible: false,
        connectedHandles: [false, false, false],
        style: undefined,
        size: "small"
    },
    [ComponentType.TransistorBJT_PNP]: {
        name: 'Transistor BJT PNP',
        value: 1,
        category: 'Transistors',
        componentType: ComponentType.TransistorBJT_PNP,
        icon: <BJTPNPIcon />,
        unit: UnitsType.Undefined,
        prefix: "",
        reference: "Q",
        type: 'transistorComponent',
        has_properties: true,
        isReferenceVisible: true,
        isValueVisible: false,
        connectedHandles: [false, false, false],
        style: undefined,
        size: "small"
    },
    [ComponentType.TransistorJFET_N]: {
        name: 'Transistor JFET N-Chan',
        value: 1,
        category: 'Transistors',
        componentType: ComponentType.TransistorJFET_N,
        icon: <JFETNIcon />,
        unit: UnitsType.Undefined,
        prefix: "",
        reference: "Q",
        type: 'transistorComponent',
        has_properties: true,
        isReferenceVisible: true,
        isValueVisible: false,
        connectedHandles: [false, false, false],
        style: undefined,
        size: "small"
    },
    [ComponentType.TransistorJFET_P]: {
        name: 'Transistor JFET P-Chan',
        value: 1,
        category: 'Transistors',
        componentType: ComponentType.TransistorJFET_P,
        icon: <JFETPIcon />,
        unit: UnitsType.Undefined,
        prefix: "",
        reference: "Q",
        type: 'transistorComponent',
        has_properties: true,
        isReferenceVisible: true,
        isValueVisible: false,
        connectedHandles: [false, false, false],
        style: undefined,
        size: "small"
    },
    [ComponentType.TransistorMOSFET_N_Enhanced]: {
        name: 'Transistor MOSFET N-Chan Enhanced',
        value: 1,
        category: 'Transistors',
        componentType: ComponentType.TransistorMOSFET_N_Enhanced,
        icon: <NChainEnhMOSFETIcon />,
        unit: UnitsType.Undefined,
        prefix: "",
        reference: "Q",
        type: 'transistorComponent',
        has_properties: true,
        isReferenceVisible: true,
        isValueVisible: false,
        connectedHandles: [false, false, false],
        style: undefined,
        size: "small"
    },
    [ComponentType.TransistorMOSFET_P_Enhanced]: {
        name: 'Transistor MOSFET P-Chan Enhanced',
        value: 1,
        category: 'Transistors',
        componentType: ComponentType.TransistorMOSFET_P_Enhanced,
        icon: <PChainEnhMOSFETIcon />,
        unit: UnitsType.Undefined,
        prefix: "",
        reference: "Q",
        type: 'transistorComponent',
        has_properties: true,
        isReferenceVisible: true,
        isValueVisible: false,
        connectedHandles: [false, false, false],
        style: undefined,
        size: "small"
    },
    [ComponentType.TransistorMOSFET_N_Depletion]: {
        name: 'Transistor MOSFET N-Chan Depletion',
        value: 1,
        category: 'Transistors',
        componentType: ComponentType.TransistorMOSFET_N_Depletion,
        icon: <NChainDepMOSFETIcon />,
        unit: UnitsType.Undefined,
        prefix: "",
        reference: "Q",
        type: 'transistorComponent',
        has_properties: true,
        isReferenceVisible: true,
        isValueVisible: false,
        connectedHandles: [false, false, false],
        style: undefined,
        size: "small"
    },
    [ComponentType.TransistorMOSFET_P_Depletion]: {
        name: 'Transistor MOSFET P-Chan Depletion',
        value: 1,
        category: 'Transistors',
        componentType: ComponentType.TransistorMOSFET_P_Depletion,
        icon: <PChainDepMOSFETIcon />,
        unit: UnitsType.Undefined,
        prefix: "",
        reference: "Q",
        type: 'transistorComponent',
        has_properties: true,
        isReferenceVisible: true,
        isValueVisible: false,
        connectedHandles: [false, false, false],
        style: undefined,
        size: "small"
    },
    [ComponentType.Inductor]: {
        name: 'Inductor',
        value: 100,
        category: 'Inductors',
        componentType: ComponentType.Inductor,
        icon: <InductorIcon />,
        unit: UnitsType.Inductance,
        prefix: "mH",
        reference: "L",
        type: 'analogComponent',
        has_properties: true,
        isReferenceVisible: true,
        isValueVisible: true,
        connectedHandles: [false, false],
        style: undefined,
        size: "small"
    },
};





export const typeGroupDiode = new Set<ComponentType>([
    ComponentType.Diode,
    ComponentType.Zener,
    ComponentType.Schottky,
    ComponentType.Tunnel,
    ComponentType.PhotoDiode,
    ComponentType.TVSDiode,
    ComponentType.Varactor,
]);


export const typeGroupResistor = new Set<ComponentType>([
    ComponentType.Resistor,
    ComponentType.Potentiometer,
]);

export const typeGroupCapacitor = new Set<ComponentType>([
    ComponentType.Capacitor,
    ComponentType.PolarisedCapacitor,
]);


export const typeGroupVariableCapacitor = new Set<ComponentType>([
    ComponentType.VariableCapacitor,
    ComponentType.TrimmerCapacitor,
]);

export const typeGroupTransistor = new Set<ComponentType>(
    [
        ComponentType.TransistorBJT_NPN,
        ComponentType.TransistorBJT_PNP,
        ComponentType.TransistorJFET_N,
        ComponentType.TransistorJFET_P,
        ComponentType.TransistorMOSFET_N_Enhanced,
        ComponentType.TransistorMOSFET_P_Enhanced,
        ComponentType.TransistorMOSFET_N_Depletion,
        ComponentType.TransistorMOSFET_P_Depletion,
    ]
);

